<% branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')[0..40] %>

defaults: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: forecast_dev

test: &test
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: forecast_test
